apiVersion: v1
kind: Service
metadata:
  name: nfs-service
  namespace: "{{  .Values.global.admin_namespace  }}"
spec:
  type: ClusterIP
  clusterIP: 10.152.183.15
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
---