---
global:
    pull_policy_pods: "IfNotPresent"
    offline_mode: "false"
    base_namespace: "base"
    flow_namespace: "flow"
    flow_jobs_namespace: "flow-jobs"
    fast_data_dir: ""
    slow_data_dir: ""
    home_dir: /root
    hostname: ""