---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctp
  namespace: {{ .Values.global.flow_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: ctp
  template:
    metadata:
      labels:
        app-name: ctp
    spec:
      containers:
        - name: ctp-container
          image: {{ .Values.global.registry_url }}/ctp:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__0.1.3
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          ports:
            - containerPort: 11112
            - containerPort: 1050
            - containerPort: 7777
          resources:
            requests:
              memory: 1024Mi
            limits:
              memory: 3000Mi
          volumeMounts:
            - name: ctp-data
              mountPath: /data/
            - name: ctp-logs
              mountPath: /opt/CTP/logs
            - name: config-file
              mountPath: /opt/CTP/config.xml
              subPath: config.xml
            - name: launcher-properties
              mountPath: /opt/CTP/Launcher.properties
              subPath: Launcher.properties
      volumes:
      - name: ctp-data
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/ctp
          type: DirectoryOrCreate
      - name: ctp-logs
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/ctp/logs
          type: DirectoryOrCreate
      - name: config-file
        configMap:
          name: ctp-config
          items:
          - key: config.xml
            path: config.xml
      - name: launcher-properties
        configMap:
          name: ctp-config
          items:
          - key: Launcher.properties
            path: Launcher.properties
      imagePullSecrets:
      - name: registry-secret
---

