---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow-app
  namespace: {{ .Values.global.base_namespace }}
  labels:
    k8s-app: airflow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: airflow-app
  template:
    metadata:
      labels:
        app-name: airflow-app
    spec:
      containers:
      - name: airflow-app
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/airflow-app-kaapana:0.1.2-vdev
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        ports:
        - name: airflow-http
          containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: airflow-http
          initialDelaySeconds: 10
          periodSeconds: 20
        resources:
          requests:
            memory: 10Mi
          limits:
            memory: 10Mi
        volumeMounts:
          - name: common-data-file
            mountPath: /app/jsons
      volumes:
      - name: common-data-file
        configMap:
          name: airflow-app-config
      imagePullSecrets:
      - name: registry-secret
