---
dependencies:
  - name: dcm4chee-chart
    version: "5.26.0"
    repository: file://../../../../services/store/dcm4chee/dcm4chee-chart
  - name: ohif-chart
    version: "4.12.26"
    repository: file://../../../../services/store/ohif-viewer/ohif-chart
  - name: minio-chart
    version: "2022.03.26"
    repository: file://../../../../services/store/minio/minio-chart
  - name: minio-console-chart
    version: "0.15.6"
    repository: file://../../../../services/store/minio-console/minio-console-chart
  - name: minio-init-chart
    version: "0.1.2"
    condition: Release.IsInstall
    repository: file://../../../../services/store/store-init/minio-init/minio-init-chart
  # TESTS
  - name: dicom-init-chart
    version: "0.1.3"
    condition: Release.IsInstall
    repository: file://../../../../services/store/store-init/dicom-init/dicom-init-chart
