apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: {{ .Values.global.store_namespace }}
spec:
  limits:
  - default:
      # cpu: {{ .Values.global.default_store_limits_cpu }}
      memory: {{ .Values.global.default_store_limits_mem }}
    defaultRequest:
      # cpu: {{ .Values.global.default_store_requests_cpu }}
      memory: {{ .Values.global.default_store_requests_mem }}
    type: Container
---
