
apiVersion: v1
kind: Service
metadata:
  name: hello-postgres-service
  namespace: "{{ .Values.global.services_namespace }}"
  #namespace: "{{ .Values.global.services_namespace }}"
  labels:
    app-name: hello-postgres
spec:
  selector:
    app-name: hello-postgres
  ports:
    - port: 5432
      targetPort: 5432