---
dependencies:
  - name: base
    version: "0.1.1"
    repository: file://deps/base
  - name: landing-page-kaapana-chart
    version: "0.1.3"
    repository: file://../../../services/base/landing-page-kaapana/landing-page-kaapana-chart
  - name: error-pages-chart
    version: "0.1.1"
    repository: file://../../../services/kaapana-core/error-pages/error-pages-chart
  - name: oAuth2-proxy-chart
    version: "7.2.1"
    repository: file://../../../services/kaapana-core/oAuth2-proxy/oAuth2-proxy-chart
  - name: keycloak-chart
    version: "16.1.1"
    repository: file://../../../services/kaapana-core/keycloak/keycloak-chart
  - name: traefik-chart
    version: "2.6"
    repository: file://../../../services/kaapana-core/traefik/traefik-chart
  - name: kube-dashboard-chart
    version: "v2.5.1"
    repository: file://../../../services/kaapana-core/kubernetes-dashboard/kube-dashboard-chart
  - name: kube-helm-chart
    version: "0.1.3"
    repository: file://../../../services/kaapana-core/kube-helm/kube-helm-chart
  - name: cert-init-chart
    version: "0.0.1"
    repository: file://../../../services/kaapana-core/core-init/cert-init/cert-init-chart
   
    