---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
  namespace: {{ .Values.global.store_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app-name: minio
    spec:
      initContainers:
        - name: init
          image: {{ .Values.global.registry_url }}/service-checker:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__1.1
          imagePullPolicy: {{ .Values.global.pull_policy_pods }}
          env:
            - name: WAIT
              value: "keycloak,keycloak-internal-service.kube-system.svc,443"
            - name: DELAY
              value: "3"
            - name: TIMEOUT
              value: "10"
      containers:
      - name: minio
        image: {{ .Values.global.registry_url }}/minio:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__2022.03.26
        imagePullPolicy: {{ .Values.global.pull_policy_pods }}
        command: ["minio"]
        args: ["server", "/export", "--address", "0.0.0.0:9000"]
        env:
        - name: MINIO_BROWSER
          value: "off"
        - name: MINIO_ROOT_USER
          value: "{{ .Values.global.credentials_minio_username }}"
        - name: MINIO_ROOT_PASSWORD
          value: "{{ .Values.global.credentials_minio_password }}"
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL
          value: "http://keycloak-external-service.kube-system.svc:80/auth/realms/kaapana/.well-known/openid-configuration"
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID
          value: "kaapana"
        - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
          value: "uQBJzc2YDzjRfj2OCT79JDShojeqAK2R"
        - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
          value: "policy"
        - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
          value: "https://{{ .Values.global.hostname }}:{{ .Values.global.https_port }}/minio-console/oauth_callback/"
        # - name: MINIO_SERVER_DEBUG
        #   value: "on"
        ports:
        - containerPort: 9000
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 1000Mi
        volumeMounts:
        - name: export  # must match the volume name, above
          mountPath: "/export"
      volumes:
      - name: export 
        hostPath:
          path: {{ .Values.global.slow_data_dir }}/minio
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
---