---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: {{ .Values.global.store_namespace }}
spec:
  template:
    metadata:
      name: minio-init
    spec:
      initContainers:
      - name: init
        image: {{ .Values.global.registry_url }}/service-checker:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__1.1
        imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
        env:
          - name: WAIT
            value: "minio,minio-service.store.svc,9000,/minio/health/live;airflow,airflow-service.flow.svc,8080"
          - name: DELAY
            value: "2"
          - name: TIMEOUT
            value: "10"
      containers:
      - name: minio-init
        image: {{ .Values.global.registry_url }}/minio-init:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__2022.03.31
        imagePullPolicy: {{ .Values.global.pull_policy_jobs }}
        resources:
          requests:
            memory: 150Mi
          limits:
            memory: 150Mi
        env:
          - name: MINIO_ACCESS_KEY
            value: {{ .Values.global.credentials_minio_username }}
          - name: MINIO_SECRET_KEY
            value: {{ .Values.global.credentials_minio_password }}
      restartPolicy: Never
      imagePullSecrets:
      - name: registry-secret
  backoffLimit: 0