---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-proxy-service
  namespace: "{{  .Values.global.helm_namespace  }}"
spec:
  selector:
    app-name: oauth2-proxy
  type: NodePort
  ports:
    - protocol: TCP
      port: 8443
      nodePort: {{ .Values.global.https_port }}
      targetPort: https
      name: https-port
---
kind: Service
apiVersion: v1
metadata:
  name: oauth2-cluster-service
  namespace: "{{  .Values.global.helm_namespace  }}"
spec:
  selector:
    app-name: oauth2-proxy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: metrics-port
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http-port
---
apiVersion: networking.k8s.io/v1 
kind: Ingress
metadata:
  name: oauth-ingress-ip
  namespace: "{{  .Values.global.helm_namespace  }}"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    kubernetes.io/ingress.global-static-ip-name: "kubernetes-ingress"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /oauth2/metrics
        pathType: ImplementationSpecific
        backend:
          service:
            name: oauth2-cluster-service
            port:
              name: metrics-port
      - path: /oauth2
        pathType: ImplementationSpecific
        backend:
          service:
            name: oauth2-cluster-service
            port:
              name: https-port
---