---
dependencies:
  - name: prometheus-chart
    version: "v2.34.0"
    repository: file://../../../../services/monitoring/prometheus/prometheus-chart
  - name: alertmanager-chart
    version: "v0.24.0"
    repository: file://../../../../services/monitoring/alert-manager/alertmanager-chart
  - name: grafana-chart
    version: "8.4.4"
    repository: file://../../../../services/monitoring/grafana/grafana-chart
  - name: kube-state-metrics-chart
    version: "v2.4.2"
    repository: file://../../../../services/monitoring/kube_state_metrics/kube-state-metrics-chart
