---
apiVersion: v1
data:
  conf.toml: |
    [tls.stores]
      [tls.stores.default]
        [tls.stores.default.defaultCertificate]
          certFile = "/ssl/tls.crt"
          keyFile = "/ssl/tls.key"
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: "{{  .Values.global.helm_namespace  }}"
---