---
apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: hello-backend
  namespace: base
  #namespace: {{ .Values.global.base_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: hello-backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app-name: hello-backend
    spec:
      containers:
      - name: hello-backend
        image: <docker-registry><docker-repo>/hello-backend:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__0.1.0
        imagePullPolicy: Always
        #imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        # command: ["tail"]
        # args: ["-f", "/dev/null"] 
        env: # Environment variables
        - name: SECRET_KEY
          value: kaapana-secret
        - name: HELLO_WORLD_USER
          value: kaapana-user
          #value: {{ .Values.hello_world_user }}
        - name: APPLICATION_ROOT
          value: "/hello-backend"
        - name: DATABASE_URL
          value: postgresql://someuser:somepassword@hello-postgres-service.base.svc:5432
        ports: # Port(s) on which your application runs
          - containerPort: 5000
        resources:
          requests:
            memory: 200Mi
          limits:
            memory: 500Mi
      imagePullSecrets:
        - name: registry-secret