apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "admin-crb-{{  .Values.global.services_namespace  }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "cluster-admin"
subjects:
  - kind: ServiceAccount
    name: kaapana-kube-admin
    namespace: "{{  .Values.global.services_namespace  }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{  .Values.global.services_namespace  }}"
  name: kaapana-kube-admin