apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: "{{ .Values.global.extensions_namespace }}"
spec:
  limits:
  - default:
      # cpu: {{ .Values.global.default_extensions_limits_cpu }}
      memory: {{ .Values.global.default_extensions_limits_mem }}
    defaultRequest:
      # cpu: {{ .Values.global.default_extensions_requests_cpu }}
      memory: {{ .Values.global.default_extensions_requests_mem }}
    type: Container
---

