---
dependencies:
  - name: airflow-chart
    version: "2.2.5"
    repository: file://../../../../services/flow/airflow/airflow-chart
  - name: ctp-chart
    version: "0.1.3"
    repository: file://../../../../services/flow/ctp/ctp-chart