---
dependencies:
  - name: kaapana-core-chart
    version: "0.1.1-vdev"
    repository: file://../../../projects/kaapana-core-chart
  - name: kibana-kaapana-chart
    version: "6.8.12-vdev"
    repository: file://../../../services/meta/kibana/kibana-kaapana/kibana-kaapana-chart
  - name: meta-init-chart
    condition: Release.IsInstall
    version: "6.8.12"
    repository: file://../../../services/meta/meta-init/meta-init-chart
  - name: elasticsearch-chart
    version: "6.8.12"
    repository: file://../../../services/meta/elasticsearch-oss/elasticsearch-chart
  - name: landing-page-kaapana-chart
    version: "0.1.3-vdev"
    repository: file://../../../services/base/landing-page-kaapana/landing-page-kaapana-chart
  - name: core-extensions-chart
    version: "0.1.0-vdev"
    repository: file://../../../services/utils/extensions-manager/core-extensions/core-extensions-chart