apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: {{ .Values.global.flow_namespace }}
spec:
  limits:
  - default:
      # cpu: {{ .Values.global.default_flow_limits_cpu }}
      memory: {{ .Values.global.default_flow_limits_mem }}
    defaultRequest:
      # cpu: {{ .Values.global.default_flow_requests_cpu }}
      memory: {{ .Values.global.default_flow_requests_mem }}
    type: Container
---
# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: default-resource-limits
#   namespace: {{ .Values.global.flow_jobs_namespace }}
# spec:
#   limits:
#   - default:
#       # cpu: {{ .Values.global.default_flow_jobs_limits_cpu }}
#       memory: {{ .Values.global.default_flow_jobs_limits_mem }}
#     defaultRequest:
#       # cpu: {{ .Values.global.default_flow_jobs_requests_cpu }}
#       memory: {{ .Values.global.default_flow_jobs_requests_mem }}
#     type: Container
# ---
