---
global:
    pull_policy_pods: "IfNotPresent"
    flow_namespace: "flow"
    flow_jobs_namespace: "flow-jobs"
    hostname: ""
    fast_data_dir: /home/kaapana
    slow_data_dir: /home/kaapana

    