---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dcm4che
  namespace: {{ .Values.global.store_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: postgres-dcm4che
  template:
    metadata:
      labels:
        app-name: postgres-dcm4che
    spec:
      containers:
        - name: postgres-dcm4che-container
          image: {{ .Values.global.registry_url }}/dcm4che-postgres:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__9.6.24-26
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          env:
            - name: STORAGE_DIR
              value: /storage/fs1
            - name: POSTGRES_DB
              value: pacsdb
            - name: POSTGRES_USER
              value: pacs
            - name: POSTGRES_PASSWORD
              value: pacs
            - name: TZ
              value: Europe/Paris
            - name: PGDATA
              value: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 150Mi
            limits:
              memory: 500Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
      - name: postgres-data
        hostPath:
           path: {{ .Values.global.fast_data_dir }}/postgres-dcm4che
           type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
---
