---
dependencies:
  - name: dcm4che-ldap
    version: "2.4.58-26.0"
    repository: file://deps/dcm4che-ldap
  - name: dcm4che-postgres
    version: "9.6.24-26"
    repository: file://deps/dcm4che-postgres
