---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-helm-deployment
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: kube-helm
  template:
    metadata:
      labels:
        app-name: kube-helm
    spec:
      containers:
      - name: kube-helm
        image: {{  .Values.global.registry_url }}{{  .Values.global.registry_project }}/kube-helm:0.1.1-vdev
        imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
        resources:
          limits:
            memory: "1Gi"
          requests:
            memory: "100Mi"
        env: # Environment variables
        - name: SECRET_KEY
          value: kaapana-secret
        - name: APPLICATION_ROOT
          value: "/kube-helm-api"
        - name: HELM_PATH
          value: "/usr/local/bin/helm"
        - name: REGISTRY_URL
          value: {{  .Values.global.registry_url }}
        - name: REGISTRY_PROJECT
          value: {{  .Values.global.registry_project }}
        - name: CHART_REGISTRY_PROJECT
          value: {{  .Values.global.chart_registry_project }}
        - name: VERSION
          value: {{ .Values.global.version }}
        - name: BASE_NAMESPACE
          value: {{  .Values.global.base_namespace }}
        - name: FLOW_NAMESPACE
          value: {{  .Values.global.flow_namespace }}
        - name: FLOW_JOBS_NAMESPACE
          value: {{  .Values.global.flow_jobs_namespace }}
        - name: PULL_POLICY_PODS
          value: {{  .Values.global.pull_policy_pods }}
        - name: PULL_POLICY_JOBS
          value: {{  .Values.global.pull_policy_jobs }}
        - name: FAST_DATA_DIR
          value: {{  .Values.global.fast_data_dir }}
        - name: SLOW_DATA_DIR
          value: {{  .Values.global.slow_data_dir }}
{{- if .Values.global.http_proxy }}
        - name: PROXY
          value: {{ .Values.global.http_proxy }}
{{- end }}
        ports: # Port(s) on which your application runs
          - containerPort: 5000
        volumeMounts:
          - name: helmextensions
            mountPath: "/root/.extensions"
          - name: helmconfig
            mountPath: "/root/.config/helm"
          - name: helmcache
            mountPath: "/root/.cache/helm"
          - name: helmlocal
            mountPath: "/root/.local/share/helm"
      volumes:
      - name: helmextensions
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/extensions
          type: DirectoryOrCreate
      - name: helmconfig
        hostPath:
          path: {{ .Values.global.home_dir }}/.config/helm
          type: DirectoryOrCreate
      - name: helmcache
        hostPath:
          path: {{ .Values.global.home_dir }}/.cache/helm
          type: DirectoryOrCreate
      - name: helmlocal
        hostPath:
          path: {{ .Values.global.home_dir }}/.local/share/helm
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
---