---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-meta-de
  namespace: {{ .Values.global.meta_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: elastic-meta
  template:
    metadata:
      labels:
        app-name: elastic-meta
    spec:
      initContainers:
          - name: volume-permissions
            image: {{ .Values.global.registry_url }}/busybox:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__1.31

            imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
            command: ["sh", "-c", "chown -R 1000:1000 /elastic_data"]
            volumeMounts:
            - mountPath: /elastic_data
              name: elasticdata
      containers:
        - name: elastic-meta-container
          image: {{ .Values.global.registry_url }}/elasticsearch-oss:{{ .Values.global.platform_abbr | default "uk" }}_{{ .Values.global.platform_version | default "0" }}__6.8.12
          imagePullPolicy:  {{ .Values.global.pull_policy_pods }}
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms{{ .Values.global.elastic_memory }}m -Xmx{{ .Values.global.elastic_memory }}m -Dlog4j2.formatMsgNoLookups=true"
          ports:
            - containerPort: 9200
          resources:
            requests:
              memory: 1500Mi
            limits:
              memory: 2000Mi
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticdata
          livenessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 15
            periodSeconds: 120
      volumes:
      - name: elasticdata
        hostPath:
          path: {{ .Values.global.fast_data_dir }}/elastic-meta
          type: DirectoryOrCreate
      imagePullSecrets:
      - name: registry-secret
---
